kaltura/playkit-js-kava

- docs/configuration.md
- src/kava.js
Change dvrThreshold units to seconds.
> fix(FEC-8311):  Live with DVR - when seeking back (more then dvrThreshold) the playbackType is not "dvr"

- karma.conf.js
- src/kava.js
- test/src/kava-model.spec.js
- test/src/kava-rate-handler.spec.js
- test/src/kava.spec.js
> fix(FEC-8354): When selecting Audio language and refresh the page, the display language returns to default (but actual audio proper)

- src/kava.js
- test/src/kava.spec.js
Change referrer string to only be URI encoded and not base64 encoded
> fix(FEC-8414): referrer should not be base64 encoded

- src/kava.js
since https://github.com/kaltura/playkit-js/pull/288
> fix: use FIRST_PLAYING event instead of PLAYBACK_STARTED

- docs/configuration-api.md
- src/kava-event-model.js
- src/kava.js
- test/src/kava-event-model.spec.js
- test/src/kava.spec.js
Need to add BUFFER_START (45) & BUFFER_END (46) events.
Send only common params.
> fix(FEC-8657): add buffer start/end events

- src/kava.js
`const percent = this.player.currentTime / this.player.duration`, returened a number above 1 on IE 11, therefore, never entred, the `if (!this._timePercentEvent.PLAY_REACHED_100 && percent === 1)` condition.
The fix: 
1. Limiting the float to have only 2 decimals at the end using the `toFixed` function.
2. Parsing the calculation using `parseFloat` function.
> fix(FEC-8606): "Play 100%" event is not sent on IE11 Win7

- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-event-model.spec.js
add `canPlay` param to the `play` event kava sends.
Also, changed the way we measure joinTime.
Untill now it was measured from the `play` event sent from the video element until the `playing` event.
> feat(FEC-8803): add 'canPlay' param to the 'play' event

- src/kava.js
Reverts the new join time calculation which was part of
https://github.com/kaltura/playkit-js-kava/pull/31
Join Time calculation needs to be defined in various edge cases (like ads). This requires handling ads event in kava which will be done in the future.
> revert: new joinTime calculation (#31)

- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-event-model.spec.js
Added the "data" field sent from the player to a new field "errorDetails" in the kava get request.
Note that we are Stringifying the data field.
HLSJS sends a custom data field which is populated by us.
In Dash we send the native Shaka error array
> feat(FEC-9071): add errorDetails field to kava error reporting

- package.json
- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-event-model.spec.js
- test/src/kava.spec.js
- yarn.lock
Adding Bandwidth, segment download time, soundMode and tabMode to 99 view report
> FEC-8975 QoS data enhancement

- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-event-model.spec.js
- test/src/kava.spec.js
adding networkConnectionType + restoring playerJSLoadTime unit test
> feat(FEC-8975): QoS Kava Enhancements - leftovers

- src/kava.js
- test/src/kava.spec.js
Refactored the networkConnectionOverhead to use PerformanceObserver due to buffer limitations of performance.getEntriesByType
> feat(FEC-9224): refactoring networkConnectionOverhead to use PerformanceObserver

- package.json
- src/kava.js
- yarn.lock
add protocol for plugin for Samsung Smart TV bug
> fix(FEC-9237): add app protocol for kava plugin

- src/kava.js
Add check on kava for performanceObserver existence
> fix(FEC-9258): Kaltura player tests fail when performanceObserver isn't define

- docs/configuration-api.md
- flow-typed/types/kava-config.js
- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-model.spec.js
- test/src/kava.spec.js
> fix(FEC-9247): add userId to kava reports

- src/kava.js
changing soundMode, tabMode and networkConnectionType - to be updated in model upon event change
Solves FEC-9220
> feat(FEC-9220): QoE tidbits

- docs/kava-events.md
- src/kava.js
- test/src/kava.spec.js
- Added view event call to kava on first play
- updated docs
solves FEC-9345
> feat(FEC-9345): send view event on first play

- src/kava.js
if not preloaded then calc jointime as playing - startload
if preloaded (auto or manual) - calc as playing -  play 
auto preload is checked in config ('auto'). manual preloaded is true when canplay occured before the first play
Solves - FEC-9575
> fix(FEC-9575): improve jointime calculation

- karma.conf.js
- test/src/kava.spec.js
Added units tests to jointime calc (original ticket was FEC-9575)
checked three scenarios - no preload, auto preload and manual preload.
solves FEC-9599
> chore(FEC-9599): add units tests to jointime calc

- docs/kava-events.md
- docs/kava-parameters.md
- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-event-model.spec.js
- test/src/kava.spec.js
…
In order to be able to differ between video start and in-stream error, we need the player to add some metadata so that those two can be separated.
Today, the position (time) is used, however this cannot be used for LIVE as the position there related to a different thing.
On the error event we need to report the following:
errorPosition=1 or errorPosition=2
1 is start error
2 is mid stream error
solves FEC-9566
In addition - fixed a failed test in view event which passed travis because of missing try catch and added missing docs for buffer_start, buffer_end and errorDetails
> feat(FEC-9566): add errorPosition (pre-playing or mid-stream) to error reporting

- src/kava.js
- test/src/kava.spec.js
When there were no new frames increasing (for example, when buffering) then the total frames and the dropped frames are same the calculation had inside 0/0 which is NaN.
I added a check that if the total frames is same then return 0 as the droppedFramesRatio.
solves FEC-9532
> fix(FEC-9532): droppedFramesRatio = NaN instead of being between 0 and 1

- docs/configuration-api.md
- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-model.spec.js
- test/src/kava.spec.js
Many of the playbacks hits are done by anonymous users and currently, we have no way to distinguish between them. 
Therefore we enable to pass persisentSessionId in kava config which will be sent in all events (once it is given - can be given in initial setup or through configure API)
solves FEC-9633
> feat(FEC-9633): send UUID with analytics events

- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-event-model.spec.js
- test/src/kava.spec.js
Fix typing.
Add screen mode in view event:
screenMode=1 (not full screen)
screenMode=2 (full screen)
> feat(FEC-10376): add full screen to screen mode on view events

- src/kava.js
Issue: kava reports to production env instead QA
Solution: add service protocol for default only.
> fix(FEC-10161): add kava analytics url from server response

- docs/configuration-api.md
- flow-typed/types/kava-http-method-type.js
- src/http-method-type.js
- src/index.js
- src/kava.js
- test/src/kava.spec.js
add `requestMethod` config (`GET` by default) and send it to `OVPAnalyticsService.trackEvent`
Depends on https://github.com/kaltura/playkit-js-providers/pull/125
Solves FEC-10615
> feat(FEC-10615): support sending Kava beacons as POST

- src/kava.js
handle promise rejection on send xhr analytics
> fix(FEC-10635): Add catch handler for Kava HTTP request

- docs/kava-parameters.md
- src/kava-event-model.js
- src/kava-model.js
- src/kava.js
- test/src/kava-model.spec.js
- test/src/kava.spec.js
add `virtualEventId` to kava beacons
> feat(FEC-11748): adding player events for EP analytics

- src/kava.js
- test/src/kava.spec.js
**the issue:**
when in pip mode and switching tabs, user is not considered as "engaged" in realtime dashboard analytics.
**root cause:** 
realtime analytics dashboard is considering "user engagement" when playback is unmuted and tab is focused. there are another 2 scenarios but they include fullscreen mode, which is irrelevant in case of pip mode.
when switching to another tab, kava plugin is sending view event with tabMode=notFocused even when in pip mode. hence, the realtime graph is showing that the user is not engaged.
**solution:**
kava plugin will report tabMode=focused in case we are in pip mode.
Note- changed also viewabilityMode to "in view" in case we are in pip mode. up until now, the viewabilityMode was "not in view" even when entering pip.
Solves FEC-11971
> fix(FEC-11971): when in PiP mode user is considered not engaged

- src/kava.js
solves: https://kaltura.atlassian.net/browse/FEC-13039
Dual-screen can change playback rate to synchronise playback of 2 medias. Kava plugin should ignore playback rate changes that made programmatically and not includes in available playback rates list.
> fix(FEC-13039):  ignore reporting playback rate values which are given to player programmatically and are not defined in the list

- src/kava.js
solves FEC-12972
fix: Listening to timeupdate event only on vod entry
> fix(FEC-12972): Player keeps polling "is-live" every 10 seconds which may overload the system

- src/kava-model.js
fix for default value for shareNetwork
> fix - SUP-37601:Social Highlights - Shares analytics not working on V7

- src/application-events-model.ts
- src/applications-events.ts
- src/enums/button-type.ts
- src/kava.ts
Add Application events analytics reporting to kava
Solves FEC-13771
Related PRs:
https://github.com/kaltura/playkit-js-related/pull/63
https://github.com/kaltura/playkit-js-call-to-action/pull/17
https://github.com/kaltura/playkit-js-hotspots/pull/317
https://github.com/kaltura/playkit-js-ivq/pull/121
https://github.com/kaltura/playkit-js-ui/pull/866
[FEC-13691]: https://kaltura.atlassian.net/browse/FEC-13691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FEC-13771): Application events analytics reporting to kava - Phase #3

- src/application-events-model.ts
- src/applications-events.ts
Send detect adblock events to kava
Related PR: https://github.com/kaltura/playkit-js-detect-ad-block/pull/9
Resolves FEC-13843
> feat(FEC-13843): Ad blocker Product analytics

- src/application-events-model.ts
- src/kava.ts
https://github.com/kaltura/playkit-js-bumper/pull/112
> fix(FEC-13943): Application events analytics reporting to kava | Under "Application" on kava dashboard numbers are displayed.

- src/kava.ts
**Issue:**
When playing only part of video by using the seekFrom the duration and currentTime is calculated according to the new times. so the position value (sent to analytics) is calculated from start time =0 (even that this is not 0 in the fully video).
**Solution:** 
If seekFrom is defined, calculate the currentTime with the seekFrom value.
Solves [SUP-42252](https://kaltura.atlassian.net/browse/SUP-42252)
[SUP-42252]: https://kaltura.atlassian.net/browse/SUP-42252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-42252): Actual view time for clips is not correct

- src/application-events-model.ts
- src/enums/player-skin.ts
- src/kava-event-model.ts
- src/kava-model.ts
- src/kava.ts
- test/e2e/application-events.model.spec.js
- test/e2e/kava-model.spec.js
- test/e2e/kava.spec.js
report `playerSkin` analytic. possible values:
- `1` - Player
- `2` - Audio
- `3` - Reels
also, fix a bug where `application` analytic for **player** events sends the wrong value (following [PR](https://github.com/kaltura/playkit-js-kava/pull/195/files)).
`application` analytic for player event should keep sending the value in `kava.config.application`, if exists.
Resolves [FEC-14469](https://kaltura.atlassian.net/browse/FEC-14469)
[FEC-14469]: https://kaltura.atlassian.net/browse/FEC-14469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FEC-14469): Report playerSkin to player events kava bucket

- src/application-events-model.ts
- src/applications-events.ts
- src/enums/application-feature.ts
- Adds new event constants for banner overlay: `BANNER_MESSAGE_DISPLAYS` and `BANNER_MESSAGE_MANUALLY_DISMISSED`.
- Integrates `BannerOverlayEvents` into the main `PluginsEvents` export.
- Updates `ApplicationEventsModel` to support the new banner overlay events and maps them to analytics models.
- Extends `ApplicationFeature` enum to include the `BANNER_OVERLAY` feature.
[FEC-14656](https://kaltura.atlassian.net/browse/FEC-14656)
[FEC-14656]: https://kaltura.atlassian.net/browse/FEC-14656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FEC-14656): Add product analytics for banner overlay plugin
