src/kava-model.js
src/kava.js

take the referrer from the config. depends on kaltura/kaltura-player-js#124

fix(FEC-8228): get referrer as config option

---

src/kava-event-model.js
src/kava-model.js
src/kava.js

Add configurable values of `applicationVersion` and `playbackContext`

feat(FEC-8296): add applicationVersion and playbackContext

---

src/kava.js

feat(FEC-8297): reset plugin on critical error

---

src/kava.js

Change the response name of viewEventsEnabled.

fix(FEC-8304): No VIEW events are sent 

---

src/kava.js

Audio track change was not reported due to incorrect event handler

fix(FEC-8308): audio track changes are not reproted

---

package.json
src/kava.js

fix(FEC-8307):  Error event is triggered also when non-critical event occurs

---

src/kava.js

Do not sent progress reports on live entries.

fix(FEC-8305):  In Live videos there are progress events sent (11-14)

---

src/kava.js

remove ready and initial tracks on TRACKS_CHANGE event.

fix(FEC-8306): No 'Play request' events are sent in web

---

src/kava.js

Change playTimeSum calculation

fix(FEC-8309): playTimeSum value in View event is incorrect (not accumulative)

---

src/kava.js

Add protection against NaN duration

fix(FEC-8317): impression event and the followup events the position value is NAN

---

src/kava.js

change logic of in _getPlaybackType

fix(FEC-8313): When playing audio entry playbackType is not "vod"

---

src/kava-rate-handler.js
src/kava.js

Remove logic of setting actualBitrate of 0 and trigger SOURCE_SELECTED event when user selected ABR mode.

fix(FEC-8320): SOURCE_SELECTED event triggered on user selection of ABR mode

---

src/kava.js

VOD and LIVE needs different play time sum calculation.

fix(FEC-8322): In view event the position and playTimeSum are not equal when stream playing continuously

---

src/kava.js
test/src/kava.spec.js

convert bps to kbps unit for reporting bitrate.

fix(FEC-8415): kava should report bitrate in kbps

---

src/kava-event-model.js
src/kava-model.js
src/kava.js
test/src/kava-model.spec.js
test/src/kava.spec.js

report `playlistId` when existing

feat(FEC-8452): playlist

---

src/kava-event-model.js
test/src/kava-event-model.spec.js

added the two params to the model sent to the server:
```
audioLanguage: model.getLanguage()
captionsLanguage: model.getCaption()
```

feat(FEC-8337): add captions and audio language to view events

---

src/kava-event-model.js
src/kava-model.js
src/kava.js
test/src/kava-event-model.spec.js
test/src/kava.spec.js

adding flavorParamsId to 99 view event

feat(FEC-8975): adding flavorParamsId

---

src/kava.js

changed the identification of id3 to support both native and hlsjs

fix(FEC-9231): support flavorParamsId in native hls

---

package.json
src/kava.js
test/src/kava.spec.js

fixed the bug and refactored the code to avoid infinite loop

fix(FEC-9251): the browser stuck after click Play button

---

src/kava-event-model.js
src/kava.js
test/src/kava-event-model.spec.js
test/src/kava.spec.js

added the networkConnectionType to play event + unit tests

fix(FEC-9269) - networkConnectionType is missing in PLAY event

---

.travis.yml
src/index.html
test/src/kava.spec.js

update ubuntu version on travis

chore: Chrome failed on travis - update travis.yml

---

docs/kava-events.md
docs/kava-parameters.md
src/kava-event-model.js
src/kava-model.js
src/kava.js
test/src/kava-event-model.spec.js
test/src/kava.spec.js

Added new event 41 to report speed playback change

feat(FEC-9343): add playback rate change event

---

docs/kava-events.md
docs/kava-parameters.md

Added segmentDownloadTime, bandwidth, tabMode, soundMode

chore(FEC-8975): QoS Enhancements - update docs

---

src/kava-event-model.js
test/src/kava-model.spec.js

application version should be sent as applicationVer. fixed in the event model building and in the spec file
solves FEC-9485

fix(FEC-9485): application version should be sent as applicationVer

---

docs/kava-events.md
src/kava-event-model.js
test/src/kava-event-model.spec.js
test/src/kava.spec.js

added playbackSpeed to view event - in kava-event-model and also added the property test in the deep equal check.
solves FEC-9344

feat(FEC-9344): adding playbackSpeed to view event

---

docs/kava-events.md
docs/kava-parameters.md
src/kava-event-model.js
test/src/kava-event-model.spec.js
test/src/kava-model.spec.js
test/src/kava.spec.js
yarn.lock

- playbackSpeed and caption have been moved to common (for all events)
- added check to send the proprty only if captions exist
- removed captionLanguage property from VIEW
- Changed unit tests to support the change
- Docs changed accordingly
Solves FEC-9652

feat(FEC-9652): report playbackSpeed and captionsLanguage in all events

---

docs/kava-parameters.md
src/kava-model.js
src/kava.js
test/src/kava.spec.js

Inspired by FEC-9658, added PRE_PLAY (3) errorPosition to be able to mark all errors before play request.
This is in order to better calc EBVS - should consider only errorPosition 1 
solves FEC-9740

feat(FEC-9740): add PRE_PLAY errorPosition to error report

---

.travis.yml
scripts/after_deploy.sh

Add kava plugin to the deployment flow
Solves FEC-10291
Related to https://github.com/kaltura/kaltura-player-js/pull/337

feat(FEC-10291): migrate analytics plugins injection from kaltura Player to server

---

package.json
yarn.lock

chore: incorrect provider version break the build

---

package.json
test/src/kava.spec.js
webpack.config.js
yarn.lock

set `libraryTarget:'var'` as default.
Change the externals to use the root only.
BREAKING CHANGE: This package is not UMD anymore
Solves FEC-10347

feat(FEC-10347): expose kaltura player as a global variable instead of UMD

---

package.json
yarn.lock

chore: update playkit-js-providers versions

---

docs/kava-parameters.md
package.json
src/kava-event-model.js
src/kava-model.js
src/kava.js
test/src/kava-event-model.spec.js
test/src/kava.spec.js
yarn.lock

Tab visibility code was copied also to kaltura, a new prop "viewabilityMode" was added to view events
solves FEC-10709, FEC-10712

feat(FEC-10709, FEC-10712): player visibility - Auto-pause when player is out of view, Autoplay only when player is in view

---

.travis.yml

chore: fix for travis

---

package.json
src/kava-event-model.js
src/kava.js
webpack.config.js
yarn.lock

Listen to related events and send events to kava
Related PR: https://github.com/kaltura/playkit-js-related/pull/34
Resolves FEC-11600

feat(FEC-11600): Related grid analytics

---

flow-typed/types/kava-config.js
src/kaltura-application.js
src/kava-event-model.js
src/kava-model.js
src/kava.js
test/src/kava-model.spec.js

Add:
* application?: string,
* kalturaApplicationVersion?: string,
* kalturaApplication?: string,
FEC-12923

feat(FEC-12923): Add missing applications data on kava  beacons & config

---

.flowconfig
.github/workflows/run_canary_full_flow.yaml
.github/workflows/run_prod.yaml
.github/workflows/run_tests.yaml
package.json
src/index.js
src/kava-timer.js
src/kava.js
test/src/kava.spec.js
webpack.config.js
yarn.lock

fix(FEC-13123): replace travis with github actions 

---

src/kava.js

solves [FEC-13181](https://kaltura.atlassian.net/browse/FEC-13181)
[FEC-13181]: https://kaltura.atlassian.net/browse/FEC-13181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13181):  Kava should send reports by POST instead of GET request

---

src/kava-timer.js

solves: https://kaltura.atlassian.net/browse/FEC-13478

fix(FEC-13478): Player stops sending view beacons when not in focus and video is silent

---

src/application-events-model.ts
src/kava.ts

KaltuaApplication param is not sent
Until now it was externally provided by the plugin config
now the requirement is to send the newly crated the PLAYRT code

fix(FEC-13773): KaltuaApplication param is not sent

---

src/application-events-model.ts
src/kava.ts

Reverts kaltura/playkit-js-kava#160

Revert "fix(FEC-13773): KaltuaApplication param is not sent"

---

src/application-events-model.ts
src/kava.ts
test/e2e/kava.spec.js

KaltuaApplication param is not sent - (with tests fixed)

fix(FEC-13773): KaltuaApplication param is not sent - (with tests fixed)

---

src/kava.ts

Prevent sent VIEW event with same time (case when playback stuck)

fix(FEC-13778): sent VIEW event only if the player has view progress

---

src/kava.ts

Kaltura player player image or audio should repory playbackType "live" or "vod"

fix(FEC-13831): Kaltura player player image or audio should repory playbackType "live" or "vod"

---

demo/plugins.html
demo/style.css
src/application-events-model.ts
src/kava.ts

Fix(FEC-13864): handle page load in kava

---

demo/plugins.html
src/application-events-model.ts
src/kava.ts

Resolves: [FEC-13943](https://kaltura.atlassian.net/browse/FEC-13943), [FEC-13933](https://kaltura.atlassian.net/browse/FEC-13933), [FEC-13932](https://kaltura.atlassian.net/browse/FEC-13932), FEC-13928
Related PR:
https://github.com/kaltura/playkit-js-bumper/pull/112
[FEC-13943]: https://kaltura.atlassian.net/browse/FEC-13943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEC-13933]: https://kaltura.atlassian.net/browse/FEC-13933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEC-13932]: https://kaltura.atlassian.net/browse/FEC-13932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 fix(FEC-13943): Application events analytics reporting to kava | Under "Application" on kava dashboard numbers are displayed.

---

package.json
src/application-events-model.ts
src/applications-events.ts
yarn.lock

Add Transcript detach analytic events
resolves: https://kaltura.atlassian.net/browse/FEC-13749

feat(FEC-13749): transcript detach analytyc events

---

src/application-events-model.ts
src/applications-events.ts
src/kava.ts

Captions product analytics
Solves: https://kaltura.atlassian.net/browse/FEC-13912

feat(FEC-13912): Captions product analytics

---

src/application-events-model.ts

resolves https://kaltura.atlassian.net/browse/FEC-13992
resolves https://kaltura.atlassian.net/browse/FEC-13993

fix(FEC-13992): change model for transcript detach (FEC-13993)

---

src/application-events-model.ts

Report media file format for media files download
Resolves FEC-13915

fix(FEC-13915): Report media file format for media files download

---

src/application-events-model.ts

Resolves FEC-13763
Related PR
https://github.com/kaltura/playkit-js-share/pull/51

 fix(FEC-13763):Application events analytics reporting to kava | ButtonValue param sent only for Share_embed_copy_click.

---

demo/index.html
demo/plugins.html
src/application-events-model.ts

fix(FEC-13928): Transcript All_tabs event sent with buttonType 3 (Search), instead of 10 (Open)

---

demo/plugins.html
src/application-events-model.ts

Resolves FEC-13845
Related PR: https://github.com/kaltura/playkit-js-ivq/pull/130

fix(FEC-13845): Add Events (used by kava analytics) | Quiz_skip_question "buttonValue" doesn't show question number.

---

demo/plugins.html
src/application-events-model.ts

fix(FEC-17015): Charge syle captions change conversion logic

---

demo/index.html

build(FEC-99999): Trigger build - canary failed

---

src/application-events-model.ts

use string instead of array
resolves: https://kaltura.atlassian.net/browse/FEC-13992
resolves: https://kaltura.atlassian.net/browse/FEC-13993

fix(FEC-13992): Change transcript detach models for drag and resize

---

src/application-events-model.ts

fix(FEC-14007): User id not being sent on application events

---

src/enums/kaltura-application.ts

feat(FEC-14309): Add Genie application id

---

src/application-events-model.ts
src/applications-events.ts

Implements requested change from https://kaltura.atlassian.net/browse/FEC-14011

fix(FEC-14011): Slide and CTA Analytics

---

src/application-events-model.ts
src/applications-events.ts

Fix placing of Vars to a correct one.
Task link: https://kaltura.atlassian.net/browse/FEC-14011
Fixes to bugs: https://kaltura.atlassian.net/browse/FEC-14355 and https://kaltura.atlassian.net/browse/FEC-14356

feat(FEC-14011): Sidescreen cta analytics

---

src/application-events-model.ts
src/types/kava-config.ts

Add whether the CTA is metadata based or player level in eventVar4 of CTA_displayed event.
- Added new eventVar4 for ApplicationEventType.PAGE_LOAD
related PR: https://github.com/kaltura/playkit-js-call-to-action/pull/36
[FEC-14341](https://kaltura.atlassian.net/browse/FEC-14341)
[FEC-14341]: https://kaltura.atlassian.net/browse/FEC-14341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FEC-14341: Metadata based CTAs - product analytics (player)

---

flow-typed/types/kava-config.js
src/application-events-model.ts
src/enums/application-feature.ts
src/enums/application.ts
src/kava-event-model.ts
src/kava-model.ts
src/kava.ts
src/types/kava-config.ts
test/e2e/application-events.model.spec.js
test/e2e/kava-model.spec.js
test/e2e/kava.spec.js

**Update all application events to be sent with the following:**
- Kaltura application = player
- Application = player type (video/audio/reels)
- Application feature = the plugin that the event is related to
- Hosting Kaltura application = the application that the player is hosted in
- Hosting Kaltura application version = the version of the application that the player is hosted in
[FEC-14288](https://kaltura.atlassian.net/browse/FEC-14288)
[FEC-14288]: https://kaltura.atlassian.net/browse/FEC-14288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(Fec 14288): Application events alignment

---

src/kava-model.ts
src/kava.ts

Make sure `IMPRESSION` event being dispatch only after plugins are registered.
[FEC-14006](https://kaltura.atlassian.net/browse/FEC-14006)
[FEC-14006]: https://kaltura.atlassian.net/browse/FEC-14006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-14006): Null being sent to event multi values var1

---

src/application-events-model.ts

resolves: https://kaltura.atlassian.net/browse/FEC-13966

fix(FEC-13966): additional stream download

---

src/application-events-model.ts
src/applications-events.ts
src/enums/application-feature.ts

resolves https://kaltura.atlassian.net/browse/FEC-14074

fix(FEC-14074): EAD events

---

package.json
src/kava-event-model.ts
src/kava-model.ts
src/kava.ts
test/e2e/kava-event-model.spec.js
yarn.lock

- add `v2-v7redirect` to `loadedPlugins` under `IMPRESSION` event, when there is a redirection from V2 to V7 player
- check `player.isV2ToV7Redirected`
Resolved FEC-14293

feat(FEC-14293): Report v2-v7 player loads to kava in Event multi vars 1

---

docs/configuration-api.md
src/kava-model.ts
src/kava.ts
src/log-failed-live-events.ts
src/types/kava-config.ts

feat(FEC-14557): log analytic failure events

---

CLAUDE.md

Adding CLAUDE.md
